### ISSUE TITLE
suppressPackageStartupMessages(library(easystats)) does not suppress Package Startup Messages

### ISSUE THREAD

**Issue by gorkang** [easystats/easystats#105]
A very minor issue. As far as I can see, there is no way to suppress the "Attaching packages" output when loading easystats.  

Below an example of the standard output, comparing with tidyverse.

``` r
library(easystats)
#> # Attaching packages
#> ✔ insight     0.13.1.1   ✔ bayestestR  0.8.3.1 
#> ✔ performance 0.7.0.1    ✔ parameters  0.12.0.1
#> ✔ see         0.6.2.1    ✔ effectsize  0.4.3.1 
#> ✔ correlation 0.6.0.1    ✔ modelbased  0.5.9   
#> ✔ report      0.2.0      
#> Warnings or errors in CRAN checks for package(s) 'bayestestR', 'parameters', 'effectsize', 'correlation'.

library(tidyverse)
#> ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──
#> ✓ ggplot2 3.3.3     ✓ purrr   0.3.4
#> ✓ tibble  3.1.0     ✓ dplyr   1.0.5
#> ✓ tidyr   1.1.3     ✓ stringr 1.4.0
#> ✓ readr   1.4.0     ✓ forcats 0.5.1
#> ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
#> x dplyr::filter() masks stats::filter()
#> x dplyr::lag()    masks stats::lag()
```

`suppressPackageStartupMessages()` does not work on the easystats.
``` r
suppressPackageStartupMessages(library(easystats))
#> # Attaching packages
#> ✔ insight     0.13.1.1   ✔ bayestestR  0.8.3.1 
#> ✔ performance 0.7.0.1    ✔ parameters  0.12.0.1
#> ✔ see         0.6.2.1    ✔ effectsize  0.4.3.1 
#> ✔ correlation 0.6.0.1    ✔ modelbased  0.5.9   
#> ✔ report      0.2.0      
#> Warnings or errors in CRAN checks for package(s) 'bayestestR', 'parameters', 'effectsize', 'correlation'.

suppressPackageStartupMessages(library(tidyverse))
```

Even an extreme version does not seem to work:

``` r
invisible(
  suppressWarnings(
    suppressMessages(
      suppressPackageStartupMessages(
        library('easystats', quietly = TRUE)
      )
    )
  )
)
#> # Attaching packages
#> ✔ insight     0.13.1.1   ✔ bayestestR  0.8.3.1 
#> ✔ performance 0.7.0.1    ✔ parameters  0.12.0.1
#> ✔ see         0.6.2.1    ✔ effectsize  0.4.3.1 
#> ✔ correlation 0.6.0.1    ✔ modelbased  0.5.9   
#> ✔ report      0.2.0      
#> Warnings or errors in CRAN checks for package(s) 'bayestestR', 'parameters', 'effectsize', 'correlation'.
```

<sup>Created on 2021-03-10 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by strengejacke** [comment]
Should work now, after you updated _insight_.

**Comment by fschaffner** [comment]
When I am loading easystats with `library("easystats")` in an Rmarkdown file that I am knitting to html, the startup messages still appear, and I haven't found a way to not print them in the html output. This isn't a problem with `library("tidyverse")`, where `message = FALSE` in the knitr chunk options turns the messages off. If you copy-paste the reproducible example below into a new .Rmd file and knit it to html you should be able to see the problem.

````
---
title: "Title"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
# The messages when loading easystats are still appearing in the html output. Adding suppressPackageStartupMessages() or quietly = TRUE doesn't help either
library("easystats")

# My easystats packages are up to date
easystats::easystats_update()

# The tidyverse messages are suppressed by message = FALSE
library("tidyverse")
```
````


<details style="margin-bottom:10px;">

<summary>Session info</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.0.4 (2021-02-15)
#>  os       macOS Big Sur 10.16         
#>  system   x86_64, darwin17.0          
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       Europe/Zurich               
#>  date     2021-04-01                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date       lib source        
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.2)
#>  backports     1.2.1   2020-12-09 [1] CRAN (R 4.0.2)
#>  cli           2.3.1   2021-02-23 [1] CRAN (R 4.0.2)
#>  crayon        1.4.1   2021-02-08 [1] CRAN (R 4.0.2)
#>  digest        0.6.27  2020-10-24 [1] CRAN (R 4.0.2)
#>  ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.2)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 4.0.1)
#>  fansi         0.4.2   2021-01-15 [1] CRAN (R 4.0.2)
#>  fs            1.5.0   2020-07-31 [1] CRAN (R 4.0.2)
#>  glue          1.4.2   2020-08-27 [1] CRAN (R 4.0.2)
#>  highr         0.8     2019-03-20 [1] CRAN (R 4.0.2)
#>  htmltools     0.5.1.1 2021-01-22 [1] CRAN (R 4.0.2)
#>  knitr         1.31    2021-01-27 [1] CRAN (R 4.0.3)
#>  lifecycle     1.0.0   2021-02-15 [1] CRAN (R 4.0.3)
#>  magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.0.2)
#>  pillar        1.5.1   2021-03-05 [1] CRAN (R 4.0.2)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.0.2)
#>  purrr         0.3.4   2020-04-17 [1] CRAN (R 4.0.2)
#>  reprex        1.0.0   2021-01-27 [1] CRAN (R 4.0.2)
#>  rlang         0.4.10  2020-12-30 [1] CRAN (R 4.0.2)
#>  rmarkdown     2.7     2021-02-19 [1] CRAN (R 4.0.2)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.2)
#>  stringi       1.5.3   2020-09-09 [1] CRAN (R 4.0.2)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 4.0.2)
#>  styler        1.4.1   2021-03-30 [1] CRAN (R 4.0.4)
#>  tibble        3.1.0   2021-02-25 [1] CRAN (R 4.0.2)
#>  utf8          1.2.1   2021-03-12 [1] CRAN (R 4.0.2)
#>  vctrs         0.3.7   2021-03-29 [1] CRAN (R 4.0.4)
#>  withr         2.4.1   2021-01-26 [1] CRAN (R 4.0.3)
#>  xfun          0.22    2021-03-11 [1] CRAN (R 4.0.2)
#>  yaml          2.2.1   2020-02-01 [1] CRAN (R 4.0.2)
#> 
#> [1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library
```

</details>

Thanks for looking into this!
